set_location_assignment PIN_AE26 -to ssd0[0]
set_location_assignment PIN_AE27 -to ssd0[1]
set_location_assignment PIN_AE28 -to ssd0[2]
set_location_assignment PIN_AG27 -to ssd0[3]
set_location_assignment PIN_AF28 -to ssd0[4]
set_location_assignment PIN_AG28 -to ssd0[5]
set_location_assignment PIN_AH28 -to ssd0[6]

set_location_assignment PIN_AJ29 -to ssd1[0]
set_location_assignment PIN_AH29 -to ssd1[1]
set_location_assignment PIN_AH30 -to ssd1[2]
set_location_assignment PIN_AG30 -to ssd1[3]
set_location_assignment PIN_AF29 -to ssd1[4]
set_location_assignment PIN_AD27 -to ssd1[6]
set_location_assignment PIN_AF30 -to ssd1[5]

set_location_assignment PIN_AB23 -to ssd2[0]
set_location_assignment PIN_AE29 -to ssd2[1]
set_location_assignment PIN_AD29 -to ssd2[2]
set_location_assignment PIN_AC28 -to ssd2[3]
set_location_assignment PIN_AD30 -to ssd2[4]
set_location_assignment PIN_AC29 -to ssd2[5]
set_location_assignment PIN_AC30 -to ssd2[6]

set_location_assignment PIN_AA24 -to ssd4[0]
set_location_assignment PIN_Y23 -to ssd4[1]
set_location_assignment PIN_Y24 -to ssd4[2]
set_location_assignment PIN_W22 -to ssd4[3]
set_location_assignment PIN_W24 -to ssd4[4]
set_location_assignment PIN_V23 -to ssd4[5]
set_location_assignment PIN_W25 -to ssd4[6]

set_location_assignment PIN_V25 -to ssd5[0]
set_location_assignment PIN_AA28 -to ssd5[1]
set_location_assignment PIN_Y27 -to ssd5[2]
set_location_assignment PIN_AB27 -to ssd5[3]
set_location_assignment PIN_AB26 -to ssd5[4]
set_location_assignment PIN_AA26 -to ssd5[5]
set_location_assignment PIN_AA25 -to ssd5[6]

set_location_assignment PIN_AD26 -to ssd3[0]
set_location_assignment PIN_AC27 -to ssd3[1]
set_location_assignment PIN_AD25 -to ssd3[2]
set_location_assignment PIN_AC25 -to ssd3[3]
set_location_assignment PIN_AB28 -to ssd3[4]
set_location_assignment PIN_AB25 -to ssd3[5]
set_location_assignment PIN_AB22 -to ssd3[6]